# PostgreSQL Database Configuration
spring.datasource.url=postgresql://postgres:lGslhgxMfDglSamlHOpCgOyhqaSGXHmz@junction.proxy.rlwy.net:11730/railway
spring.datasource.username=postgres
spring.datasource.password=11730
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
